# Generated by Django 5.1.2 on 2024-10-08 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='type_Subscription',
            new_name='type_subscription',
        ),
    ]
