# Generated by Django 5.1.2 on 2024-10-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='Please enter the default value as valid Python.', max_length=20),
            preserve_default=False,
        ),
    ]
